import type { Metadata } from "next";
import "@/app/ui/globals.css";
import 'primereact/resources/themes/saga-blue/theme.css'; 
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import SideNav from "@/app/ui/component/Dashboard/SideNav";
import Header from "@//app/ui/component/Dashboard/Header";


export const metadata: Metadata = {
  title: "Nextjs Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen flex-col">

      <div>
        {/* NOTE: Header and SideNavbar will always be present*/}
        <div className="fixed left-0 top-0 w-full z-50">
          <Header />
        </div>

        <div className="fixed w-64 left-0 top-16 h-full z-40" >
          <SideNav />
        </div>
      </div>

      <main className="ml-64 pt-20 px-6 md:px-12 overflow-y-auto flex-1">
        {children}
      </main>
    </div>
  );
}