import type { Metadata } from "next";
import "@/app/ui/globals.css";
import 'primereact/resources/themes/saga-blue/theme.css'; 
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import SideNav from "@/app/ui/component/Dashboard/SideNav";


export const metadata: Metadata = {
  title: "Nextjs Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen flex-col md:flex-row">
      {/* NOTE: SideNavbar will always be present*/}
      <div className="fixed left-0 top-0 h-screen w-auto bg-white shadow-lg rounded-sm">
        <SideNav />
      </div>
      <div className="grow md:ml-auto p-6 md:p-12 overflow-y-auto">
          {children}
      </div>
    </div>
  );
}