import type { Metadata } from "next";
import "@/app/ui/globals.css";
import 'primereact/resources/themes/saga-blue/theme.css'; 
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import SideNav from "@/app/ui/component/Common/SideNav";
import Header from "@/app/ui/component/Common/Header";


export const metadata: Metadata = {
  title: "Nextjs Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen w-screen flex-col">

      {/* NOTE: Header and SideNavbar will always be present*/}
      <Header />

      <div className="flex flex-1 overflow-hidden" >
        <SideNav />

        <main className="overflow-y-auto flex-1 p-6">
          {children}
        </main>
      </div>
    </div>
  );
}